##
## EPITECH PROJECT, 2021
## B-CNA-410-STG-4-1-groundhog-pierre.jeannin
## File description:
## Makefile
##

SRC =   groundhog.py

OUTPUT = groundhog #nom de l'exectutable

all:
	@rm -rf $(OUTPUT)
	@cp $(SRC) $(OUTPUT)
	@echo "Compilation ended"

clean:
	@echo "Clean"

fclean: clean
	@rm -rf $(OUTPUT)
	@echo "Fclean"

re: fclean all